In [12]:
import pandas as pd

In [16]:
df_ipl = pd.read_csv('ipl_matches.csv')

df_ipl.head(10)

,match_id,season,city,team1,team2,winner,win_by_runs,win_by_wickets,player_of_match
0,1,2023,Ahmedabad,Chennai Super Kings,Gujarat Titans,Gujarat Titans,0,5,Rashid Khan
1,2,2023,Mohali,Punjab Kings,Kolkata Knight Riders,Punjab Kings,7,0,Arshdeep Singh
2,3,2023,Lucknow,Lucknow Super Giants,Delhi Capitals,Lucknow Super Giants,50,0,Mark Wood
3,4,2023,Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,Rajasthan Royals,72,0,Jos Buttler
4,5,2023,Bengaluru,Mumbai Indians,Royal Challengers Bengaluru,Royal Challengers Bengaluru,0,8,Virat Kohli
5,6,2023,Chennai,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,12,0,Moeen Ali
6,7,2023,Delhi,Gujarat Titans,Delhi Capitals,Gujarat Titans,0,6,Sai Sudharsan
7,8,2023,Guwahati,Rajasthan Royals,Punjab Kings,Punjab Kings,5,0,Nathan Ellis
8,9,2023,Kolkata,Kolkata Knight Riders,Royal Challengers Bengaluru,Kolkata Knight Riders,81,0,Shardul Thakur
9,10,2023,Mumbai,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,0,7,Ajinkya Rahane

In [19]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [20]:
df_expenses = pd.read_excel('mobile_expenses.xlsx')
print(df_expenses.tail(3))

    Month    Plan_Type  Data_Addon_Cost  OTT_Subscription  Total_Expense
5    June  Prepaid 719               50               149            918
6    July  Prepaid 299                0               149            448
7  August  Prepaid 299               29               149            477

In [21]:

df_zomato = pd.read_csv('zomato_restaurants.csv')

df_zomato.info()

print(df_zomato.describe())

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   restaurant_id     15 non-null     int64
 1   restaurant_name   15 non-null     str
 2   cuisine           15 non-null     str
 3   rating            15 non-null     float64
 4   votes             15 non-null     int64
 5   avg_cost_for_two  15 non-null     int64
dtypes: float64(1), int64(3), str(2)
memory usage: 852.0 bytes
       restaurant_id     rating        votes  avg_cost_for_two
count      15.000000  15.000000    15.000000         15.000000
mean     1008.000000   4.133333  1460.000000        746.666667
std         4.472136   0.289499  1084.520961        459.217761
min      1001.000000   3.700000   410.000000        250.000000
25%      1004.500000   3.900000   670.000000        425.000000
50%      1008.000000   4.100000  1100.000000        550.000000
75%      1011.500000   4.350000  1950.000000       1025.000000
max      1015.000000   4.600000  4200.000000       1600.000000

In [22]:
df_ipl = pd.read_csv('ipl_matches.csv')

df_ipl.head(20).to_csv('filtered_data.csv', index=False)

df_filtered = pd.read_csv('filtered_data.csv')
print("Total rows exported:", len(df_filtered))
df_filtered.head()

Total rows exported: 20

,match_id,season,city,team1,team2,winner,win_by_runs,win_by_wickets,player_of_match
0,1,2023,Ahmedabad,Chennai Super Kings,Gujarat Titans,Gujarat Titans,0,5,Rashid Khan
1,2,2023,Mohali,Punjab Kings,Kolkata Knight Riders,Punjab Kings,7,0,Arshdeep Singh
2,3,2023,Lucknow,Lucknow Super Giants,Delhi Capitals,Lucknow Super Giants,50,0,Mark Wood
3,4,2023,Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,Rajasthan Royals,72,0,Jos Buttler
4,5,2023,Bengaluru,Mumbai Indians,Royal Challengers Bengaluru,Royal Challengers Bengaluru,0,8,Virat Kohli

In [23]:
df_custom = pd.read_csv('zomato_restaurants.csv')

df_custom.to_excel('automobile_analysis.xlsx', sheet_name='Analysis2024', index=False)

excel_file = pd.ExcelFile('automobile_analysis.xlsx')
print("Confirmed Excel sheet name:", excel_file.sheet_names)

Confirmed Excel sheet name: ['Analysis2024']